# Generated by Django 5.2.1 on 2025-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('related_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_entity_id', models.CharField(blank=True, max_length=36, null=True)),
                ('message', models.TextField()),
                ('send_time', models.DateTimeField()),
                ('notification_type', models.CharField(max_length=50)),
                ('is_sent', models.IntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
    ]
