# Generated by Django 5.2.1 on 2025-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInstitutions',
            fields=[
                ('institution_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('blackboard_api_base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'academic_institutions',
                'managed': False,
            },
        ),
    ]
