# Generated by Django 5.2.1 on 2025-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streaks',
            fields=[
                ('streak_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('streak_type', models.CharField(max_length=50)),
                ('current_streak_count', models.IntegerField()),
                ('longest_streak_count', models.IntegerField()),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'streaks',
                'managed': False,
            },
        ),
    ]
