# Generated by Django 5.2.1 on 2025-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('goal_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_achieved', models.IntegerField(blank=True, null=True)),
                ('achieved_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInstitutionConnections',
            fields=[
                ('connection_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('blackboard_access_token', models.TextField(blank=True, null=True)),
                ('blackboard_refresh_token', models.TextField(blank=True, null=True)),
                ('blackboard_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_institution_connections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('preference_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('preferred_study_times', models.JSONField(blank=True, null=True)),
                ('preferred_study_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('preferred_break_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('weekly_study_hours_target', models.IntegerField(blank=True, null=True)),
                ('learning_style', models.JSONField(blank=True, null=True)),
                ('focus_issues', models.TextField(blank=True, null=True)),
                ('procrastination_tendency', models.TextField(blank=True, null=True)),
                ('sleep_bed_time', models.TimeField(blank=True, null=True)),
                ('sleep_wake_time', models.TimeField(blank=True, null=True)),
                ('preferred_reward_system', models.TextField(blank=True, null=True)),
                ('notification_email', models.IntegerField(blank=True, null=True)),
                ('notification_web_push', models.IntegerField(blank=True, null=True)),
                ('notification_in_app', models.IntegerField(blank=True, null=True)),
                ('notification_timing_before_study_minutes', models.IntegerField(blank=True, null=True)),
                ('notification_daily_summary_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
